### ISSUE TITLE
升级v1.10.0失败

### ISSUE THREAD

**Issue by yaof2** [chandelures/openwrt-clash#78]
大佬，fork了你的源码，clash官方升级到了v1.10.0了。我修改了2个地方，一直编译不成功。1、Makefile中的PKG_VERSION:=1.10.0. 2、将hash=skip  不能成功。  改为1.9.0  同事hash=skip，能成功。应该不是hash的问题。求解。等你升级。

**Comment by chandelures** [comment]
Clash v1.10.0需要golang 1.18, 但是openwrt官方编译链中的golang并没有更新到1.18, 因此编译不成功。
https://github.com/Dreamacro/clash/releases/tag/v1.10.0
https://openwrt.org/packages/pkgdata/golang

**Comment by yaof2** [comment]
我看见了。所以自己建了golang。修改了链接。也是不成功。看来只有等了

**Comment by chandelures** [comment]
#79
